version: '3.9'

services:
  backend:
    build: ./backend-flask
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./backend-flask/:/usr/src/app/
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    depends_on:
      - db
      - dynamodb-local

  frontend:
    build: ./frontend-react-js
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react-js/src:/app/src
    environment:
      VITE_REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

networks:
  internal-network:
    driver: bridge
    name: cruddur

volumes:
  postgres_data:
    driver: local
